### ISSUE TITLE
Updater skips the file if it already has the current year in copyright

### ISSUE THREAD

**Issue by phated** [update/updater-license#5]
I understand not wanting to update the year again but I typically need to update the copyright holders (github repo creation inserts "gulp" but I need to put individual member names).

**Comment by jonschlinkert** [comment]
> but I need to put individual member names

This is doable, where should we get the names? We can easily use the `contributors` in package.json or something like that.

**Comment by phated** [comment]
`defaults.js`?  I have a static contributor list

**Comment by jonschlinkert** [comment]
meaning a `defaults.js` in global config? just thinking out loud, we can use the `update` property in package.json for that too. or `defaults.js` or something similar in `~/.update/`... any thoughts on those?

**Comment by phated** [comment]
I don't like basing anything on `package.json` because that requires running things in a specific order.  I think it needs to come from some config on the user's system but also be configurable programmatically.

**Comment by jonschlinkert** [comment]
> I don't like basing anything on package.json because that requires running things in a specific order.

It's totally doable to have the config the way you prefer it. But that also makes it impossible for anyone besides you to maintain the project.

**Comment by phated** [comment]
That's why it should be configurable programmatically so I can create a "updater-gulp" that does everything exactly the way I want it and doesn't rely on `~/templates` or `~/.update`

**Comment by jonschlinkert** [comment]
I see, so you're more focused on the initial creation, following specific conventions? Just trying to understand the flow so I can think of the best way to do this (and potentially simplify our own workflow). 

Initially, I thought you meant for all of your projects, even after creating them (and maybe you are, but I'll need clarification on that if so). To explain through example, we have 1,300+ projects, where we try to keep as much generalized as possible so that we can just run `update` or `verb` and it "just works". In order for that to happen, it's imperative that the data always be in the repo itself, otherwise we'd have to somehow update the global config every time some detail in a project changes, or between my setup and other maintainers, etc.

**Comment by phated** [comment]
Alright, so this is the **create** workflow I'd like to support (step by step):
1. Create repository with LICENSE/README.md/gitignore using the Github website UI
2. Pull repository using `git clone`
3. `cd` into project directory
4. Run `update` to create/update the default files for the project - This includes gitignore/LICENSE/eslintrc/jscsrc/editorconfig/test directory(with .eslintrc)/travis.yml/appveyor.yml (I suppose `package.json` can be in here but mine vary enough that it would be a minimal one and I usually just copy it over).
5. Commit over the initial commit with `git commit --amend`

The **update** workflow should be something like:
1. Install `updater-gulp` as a devDep (it'd be included in my devDep list)
2. Run `npm run update` which would be an npm-script that runs `update gulp` (or something like that) - basically I want everything installed locally and behind an npm-script

**Comment by doowb** [comment]
I was thinking of how this worked to in regards to `updater-eslint`. I think we should allow an `update` property in `package.json` that can be used for configuration options of specific updaters, then look for config files, then fallback to the defaults in the updater. I think this will allow keeping configuration close to the project once it's been setup (and in this case, if someone needs to be added to the license that's not in other projects, then it's easier to do). It will also allow you to have a global config or create an updater that just includes `updater-license` and sets the options to be used when creating new projects.

This is similar to how it's handled in `verb` and you'll see that we have a `verb` property in the `package.json` with configuration options. I know we've talked about having other configuration options before and specifying how those work for all updaters will make these types of issues just an option or configuration choice for the individual updater.

**Comment by jonschlinkert** [comment]
@phated awesome workflow. totally doable, we might have everything we need to do almost all of it. if not, we're very close.  

@doowb let's chat about `generate-gh-repo` and how we can use that for that first step. We can easily add tasks or prompts for the license/readme part, then one to pull. thoughts?

**Comment by doowb** [comment]
> let's chat about generate-gh-repo

We can do something where when `gen gh-repo` is run in an empty folder, it will prompt what other generators to run or something like that before actually creating the github repo. That should be moved to the `generate-gh-repo` repository probably.

**Comment by jonschlinkert** [comment]
> That should be moved to the generate-gh-repo repository probably.

maybe instead we should create a new generator: `generate-next` that is used as a plugin. All it would do is ask: "Do you want to run another generator?" and present the list of generators to run. The message could be customizable. But I think in this case it would be perfect because you'd want to prompt to generate the github repo first, then pull down the repo, then run `next`.

**Comment by jonschlinkert** [comment]
ooh, i have an idea. forget all that.. Let me try something, not sure how long this will take
